insert into common_respondenttype values('CRP_ap','Cluster Resource Persons (CRPs)', 'ap', 'AC');
insert into common_respondenttype values('MEO','Mandal Education Officer (MEOs)', 'ap', 'AC');
insert into common_respondenttype values('DEO_ap','District Education Officer (DEOs)', 'ap', 'AC');
insert into common_respondenttype values('BEO_ap','Block Education Officer (BEOs)', 'ap', 'AC');
insert into common_respondenttype values('BRP_ap','Block Resource Persons (BRPs)', 'ap', 'AC');
insert into common_respondenttype values('DIET_Lec','DIET lecturer', 'ap', 'AC');
insert into common_respondenttype values('AMO','Academic Monitoring Officer (AMOs)', 'ap', 'AC');
insert into common_respondenttype values('CRP_gj','Cluster Resource Persons (CRPs)', 'gj', 'AC');
insert into common_respondenttype values('DEO_gj','District Education Officer (DEOs)', 'gj', 'AC');
insert into common_respondenttype values('BEO_gj','Block Education Officer (BEOs)', 'gj', 'AC');
insert into common_respondenttype values('BRP_gj','Block Resource Persons (BRPs)', 'gj', 'AC');
insert into common_respondenttype values('DIET_Lec_gj','DIET lecturer', 'gj', 'AC');
