# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 06:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0024_auto_20171222_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('questiongroup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessments.QuestionGroup')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('school_id', models.IntegerField(blank=True, null=True)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None)),
                ('date_of_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_invalid', models.BooleanField(default=False)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('qg_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ivrs.QuestionGroupType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
