# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-31 07:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrs', '0002_incomingnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), null=True, size=None),
        ),
    ]
