DELETE from schools_management;
INSERT INTO schools_management (id, name) VALUES
(1, 'Department of Education'),
(2, 'SWD'),
(3, 'Local Body'),
(4, 'Pvt. Aided'),
(5, 'Pvt. Unaided'),
(6, 'Others'),
(7, 'Approved'),
(8, 'SSA'),
(9, 'KGBV'),
(10, 'Pvt. Aided SC'),
(11, 'Pvt. Aided ST'),
(12, 'Jawahar'),
(13, 'Central'),
(14, 'Sainik'),
(15, 'Central Govt.'),
(16, 'NRI'),
(17, 'Madrasa-Aided'),
(18, 'Madrasa-Unaided'),
(19, 'Arabic-Aided'),
(20, 'Arabic-Unaided'),
(21, 'Sanskrit-Aided'),
(22, 'Pvt. Unaided SC'),
(23, 'Pvt. Aided ST'),
(24, 'Un-Recognized'),
(25, 'Tribal/Social Welfare Dept.');