language: python
python:
  - "3.5"
services:
  - postgresql
before_install:
  - sudo apt-get install libgdal-dev
install:
  - "pip install -r requirements.txt"
before_script:
  - psql -U postgres createdb -E UTF8 -T template0 test_ilp
  - psql -U postgres -d test_ilp -c "create extension postgis;"
script:
  - python manage.py test 