version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ilp
permissions:
  - object: /home/ubuntu/ilp
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/install_deps.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/restart_services.sh
      timeout: 180
