version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/python:3.5.3
      - image: circleci/postgres:9.3
        environment:
          POSTGRES_USER: postgres 
          POSTGRES_DB: test_ilp