version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/ilp
    steps:
      - checkout
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      DATABASE_URL: postgresql://ubuntu:@127.0.0.1:5432/test_ilp
      POSTGRES_USER: ubuntu
      POSTGRES_DB: test_ilp

  deploy:
    docker:
      - image: circleci/python:3.6.1
        command: /sbin/init
    working_directory: ~/ilp
    steps:
      - checkout
      - run:
          name: Install pip
          command: 'sudo apt-get update && sudo apt-get install -y python-pip'
      - run:
          name: Install awscli
          command: 'sudo pip install awscli'
      - run:
          name: Create venv
          command: 'python3 -m venv venv | source venv/bin/activate && pip install -r requirements/test.txt'
      - run:
          name: Report creation
          command: 'mv ilp/settings/ci_settings.py.sample ilp/settings/ci_settings.py | venv/bin/activate && coverage run --source='.' --omit='venv/*' manage.py test boundary users assessments | venv/bin/activate && coverage report | venv/bin/activate && coverage html |
      - run:
          name: Move artifacts
          command: 'mkdir -p /tmp/artifacts | mv htmlcov /tmp/artifacts'
      
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: circleci-upgrade_test
