version: 2
general:
  branches:
    only:
      - master
      - /*-test/
jobs:
  build:
    working_directory: ~/ilp
    docker:
      - image: circleci/python:3.6.1
      - image: postgres:9.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_ilp
    steps:
      - checkout
      - run:
          command: |
            mv ilp/settings/ci_settings.py.sample ilp/settings/ci_settings.py  
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup postgres and postgis
          command: |
            sudo -u postgres psql -d test_ilp -c "CREATE EXTENSION postgis;"
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo apt-get install libgdal-dev
            pip install -r requirements/test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running migration and loading up fixtures.
          command: |
            . venv/bin/activate
            python manage.py migrate
            python manage.py loaddata apps/common/fixtures/*.json
            python manage.py loaddata apps/*/tests/fixtures/*.json
            mkdir -p /tmp/artifacts
      - run:
          name: Running tests.
          command: |
            . venv/bin/activate
            coverage run --source='.' --omit='venv/*' manage.py test schools
      - run:
          name: Coverage report.
          command: |
            . venv/bin/activate
            coverage report
            coverage html
            mv htmlcov /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
