version: 2
general:
  branches:
    only:
      - master
      - /*-test/
jobs:
  build:
    working_directory: ~/ilp
    docker:
      - image: circleci/python:3.6.1
      - image: mdillon/postgis:9.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_ilp
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo apt-get install libgdal-dev
            pip install -r requirements/test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  test:
    override:
      - python manage.py loaddata apps/common/fixtures/*.json
      - python manage.py loaddata apps/*/tests/fixtures/*.json
      - coverage run --source='.' manage.py test schools
      - coverage html
    post:
      - mkdir -p $CIRCLE_ARTIFACTS/coverage-report
      - mv htmlcov $CIRCLE_ARTIFACTS/coverage-report
