version: 2
general:
  branches:
    only:
      - master
      - /*-test/
jobs:
  build:
    working_directory: ~/ilp
    docker:
      - image: circleci/python:3.6.1
      - image: mdillon/postgis:9.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: test_ilp
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Basic project setup
          command: |
            python3 -m venv venv
            . venv/bin/activate
            mv ilp/settings/ci_settings.py.sample ilp/settings/ci_settings.py
            sudo apt-get install libgdal-dev
            sudo apt-get install -y postgresql-client
            pip install -r requirements/test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests.
          command: |
            . venv/bin/activate
            coverage run --source='.' --omit='venv/*' manage.py test schools
      - run:
          name: Coverage report.
          command: |
            . venv/bin/activate
            coverage report
            coverage html
            mkdir -p /tmp/artifacts
            mv htmlcov /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
