
version: 2
jobs:
  build:
    docker:
       - image: circleci/python:3.6.2
          environment:
           FLASK_CONFIG: testing
           TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
       - image: circleci/postgres:9.6.5
         environment:
           POSTGRES_USER: root
           POSTGRES_DB: circle_test
           POSTGRES_PASSWORD: ""
steps:
  - checkout
  - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "requirements.txt" }}
      - v1-dependencies-

  - run:
      name: install dependencies
      command: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

  - save_cache:
      paths:
        - ./venv
      key: v1-dependencies-{{ checksum "requirements.txt" }}
  - run:
      name: run tests
      command: |
        . venv/bin/activate
        python manage.py test

  - store_artifacts:
      path: test-reports
      destination: test-reports
