version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/ilp
    steps:
      - checkout
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      DATABASE_URL: postgresql://ubuntu:@127.0.0.1:5432/test_ilp
      POSTGRES_USER: ubuntu
      POSTGRES_DB: test_ilp

  deploy:
    docker:
      - image: circleci/python:3.6-jessie-node
        command: /sbin/init
    working_directory: ~/ilp
    steps:
      - checkout
      - run:
          name: Install pip
          command: 'sudo apt-get update && sudo apt-get install -y python-pip'
      - run:
          name: Install awscli
          command: 'sudo pip install awscli'
      
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: circleci-upgrade_test
