version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
        environment:
          DATABASE_URL: postgresql://ubuntu:@127.0.0.1:5432/test_ilp
          POSTGRES_USER: ubuntu 
          POSTGRES_DB: test_ilp

    working_directory: ~/ilp
    steps:
      - checkout
  deploy:
    docker:
      # Python image required for AWS client
      - image: circleci/python:3.6.2
    working_directory: ~/ilp
    steps:
      - checkout
      - run:
          name: Install pip
          command: 'sudo apt-get update && sudo apt-get install -y python-pip'
      - run:
          name: Install awscli
          command: 'sudo pip install awscli'
      - run:
          name: install dependencies
          command: |
            'python3 -m venv venv'
            '. venv/bin/activate'
            'pip install -r requirements/test.txt'

  test:
    '- . venv/bin/activate && coverage run --source='.' --omit='venv/*' manage.py test boundary users assessments'
    '- . venv/bin/activate && coverage report'
    '- . venv/bin/activate && coverage html'
    '- mkdir -p /tmp/artifacts'
    '- mv htmlcov /tmp/artifacts '
    
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: circleci-upgrade



  
