# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='start_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(max_length=20),
        ),
    ]
