# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionGroupInstitutionAssociation',
            new_name='QuestionGroup_Institution_Association',
        ),
        migrations.RenameModel(
            old_name='QuestionGroupQuestions',
            new_name='QuestionGroup_Questions',
        ),
        migrations.RenameModel(
            old_name='QuestionGroupStudentGroupAssociation',
            new_name='QuestionGroup_StudentGroup_Association',
        ),
    ]
