# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20170824_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondenttype',
            name='id',
        ),
        migrations.AddField(
            model_name='respondenttype',
            name='char_id',
            field=models.CharField(default='VR', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
