# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20170816_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displaytype',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='responsetype',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='surveytype',
            old_name='desc',
            new_name='description',
        ),
    ]
