# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_20170828_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiongroup',
            old_name='verison',
            new_name='version',
        ),
        migrations.AlterField(
            model_name='question',
            name='display_text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=300),
        ),
    ]
