# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20170829_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergroup_institution',
            name='comments',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='answergroup_student',
            name='comments',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='answergroup_studentgroup',
            name='comments',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
