# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_auto_20171003_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answergroup_institution',
            name='respondent_type',
        ),
        migrations.RemoveField(
            model_name='answergroup_student',
            name='respondent_type',
        ),
        migrations.RemoveField(
            model_name='answergroup_studentgroup',
            name='respondent_type',
        ),
    ]
