# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_auto_20171006_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='answergroup_institution',
            name='respondent_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.RespondentType'),
        ),
        migrations.AddField(
            model_name='answergroup_student',
            name='respondent_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.RespondentType'),
        ),
        migrations.AddField(
            model_name='answergroup_studentgroup',
            name='respondent_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.RespondentType'),
        ),
    ]
