# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_survey_admin0'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTag',
            fields=[
                ('char_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTagMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Survey')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.SurveyTag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='surveytagmapping',
            unique_together=set([('survey', 'tag')]),
        ),
    ]
