# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_auto_20171124_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionimages',
            name='reponseid',
        ),
        migrations.AddField(
            model_name='institutionimages',
            name='answergroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessments.AnswerGroup_Institution'),
            preserve_default=False,
        ),
    ]
