# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_auto_20171110_1114'),
        ('assessments', '0015_surveyansagg_surveyboundaryagg_surveyclassansagg_surveyclassgenderagg_surveydetailsagg_surveyelectio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTagInstitutionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Institution')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.SurveyTag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='surveytaginstitutionmapping',
            unique_together=set([('tag', 'institution')]),
        ),
    ]
