# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_auto_20171204_1140'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='surveyclassansagg',
            table='mvw_survey_class_ans_agg',
        ),
        migrations.AlterModelTable(
            name='surveyclassgenderagg',
            table='mvw_survey_class_gender_agg',
        ),
        migrations.AlterModelTable(
            name='surveyelectionboundaryagg',
            table='mvw_survey_electionboundary_agg',
        ),
    ]
