# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 03:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_auto_20171208_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergroup_student',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='answergroup_student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answergroup_student',
            name='group_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answerinstitution',
            name='answergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.AnswerGroup_Institution'),
        ),
        migrations.AlterField(
            model_name='answerinstitution',
            name='double_entry',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
