# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_auto_20171211_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyClassQuestionKeyAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
                ('num_correct_assessments', models.IntegerField(db_column='num_correct_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_class_questionkey_agg',
                'managed': False,
            },
        ),
    ]
