# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_surveyclassquestionkeyagg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestionGroupQuestionKeyAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_id', models.CharField(db_column='questiongroup_id', max_length=100)),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_questiongroup_questionkey_agg',
                'managed': False,
            },
        ),
    ]
