# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0024_auto_20171222_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='survey_on',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_on',
            field=models.ForeignKey(default='institution', on_delete=django.db.models.deletion.CASCADE, to='assessments.SurveyOnType'),
            preserve_default=False,
        ),
    ]
