# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-03 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0019_auto_20171229_0844'),
        ('assessments', '0026_surveyquestiongroupgenderagg_surveyquestiongroupgendercorrectansagg'),
    ]

    operations = [
    ]
