# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_merge_20180103_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInstitutionQuestionAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('question_desc', models.CharField(db_column='question_desc', max_length=200)),
                ('score', models.BooleanField(db_column='score')),
            ],
            options={
                'db_table': 'mvw_survey_institution_question_agg',
                'managed': False,
            },
        ),
    ]
