# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0028_surveyinstitutionquestionagg'),
    ]

    operations = [
        migrations.AddField(
            model_name='answergroup_institution',
            name='mobile',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='answergroup_student',
            name='mobile',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='answergroup_studentgroup',
            name='mobile',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='questions',
            field=models.ManyToManyField(through='assessments.QuestionGroup_Questions', to='assessments.Question'),
        ),
    ]
