# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_auto_20180109_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyBoundaryQuestionGroupAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_desc', models.CharField(db_column='question_desc', max_length=200)),
                ('answer_option', models.CharField(db_column='answer_option', max_length=100)),
                ('num_answers', models.IntegerField(db_column='num_answers')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_questiongroup_ans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionGroupAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_desc', models.CharField(db_column='question_desc', max_length=200)),
                ('answer_option', models.CharField(db_column='answer_option', max_length=100)),
                ('num_answers', models.IntegerField(db_column='num_answers')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_questiongroup_ans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionGroupAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_desc', models.CharField(db_column='question_desc', max_length=200)),
                ('answer_option', models.CharField(db_column='answer_option', max_length=100)),
                ('num_answers', models.IntegerField(db_column='num_answers')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_questiongroup_ans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionGroupDetailsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_schools', models.IntegerField(db_column='num_schools')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
                ('num_children', models.IntegerField(db_column='num_children')),
                ('num_users', models.IntegerField(db_column='num_users')),
                ('last_assessment', models.DateField(db_column='last_assessment')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_questiongroup_details_agg',
            },
        ),
    ]
