# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20180111_1021'),
        ('common', '0002_religion_studentcategory'),
        ('assessments', '0032_surveyboundaryquestiongroupagg_surveyinstitutionquestiongroupagg'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytaginstitutionmapping',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.AcademicYear'),
        ),
        migrations.AlterUniqueTogether(
            name='surveytaginstitutionmapping',
            unique_together=set([('tag', 'institution', 'academic_year')]),
        ),
    ]
