# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0032_surveyboundaryquestiongroupagg_surveyinstitutionquestiongroupagg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTagMappingAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_schools', models.IntegerField(db_column='num_schools')),
                ('num_children', models.IntegerField(db_column='num_children')),
            ],
            options={
                'db_table': 'mvw_survey_tagmapping_agg',
                'managed': False,
            },
        ),
    ]
