# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-17 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0033_surveytagmappingagg'),
        ('assessments', '0033_auto_20180116_2202'),
    ]

    operations = [
    ]
