# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-17 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_religion_studentcategory'),
        ('assessments', '0034_merge_20180117_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTagClassMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(max_length=20)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.AcademicYear')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.SurveyTag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='surveytagclassmapping',
            unique_together=set([('tag', 'sg_name', 'academic_year')]),
        ),
    ]
