# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_auto_20180117_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyBoundaryClassAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('answer_option', models.CharField(db_column='answer_option', max_length=100)),
                ('num_answers', models.IntegerField(db_column='num_answers')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_class_ans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryClassGenderAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_class_gender_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryClassGenderCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_class_gender_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryClassQuestionKeyAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_class_questionkey_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryClassQuestionKeyCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_class_questionkey_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQuestionGroupGenderAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_questiongroup_gender_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQuestionGroupGenderCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_questiongroup_gender_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQuestionGroupQuestionKeyAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_questiongroup_questionkey_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQuestionGroupQuestionKeyCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_questiongroup_questionkey_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQuestionKeyAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_questionkey_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQuestionKeyCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_questionkey_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryRespondentTypeAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_schools', models.IntegerField(db_column='num_schools')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
                ('num_children', models.IntegerField(db_column='num_children')),
                ('last_assessment', models.DateField(db_column='last_assessment')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_respondenttype_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryUserTypeAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(db_column='user_type', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_schools', models.IntegerField(db_column='num_schools')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
                ('num_children', models.IntegerField(db_column='num_children')),
                ('last_assessment', models.DateField(db_column='last_assessment')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_boundary_usertype_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionClassAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('answer_option', models.CharField(db_column='answer_option', max_length=100)),
                ('num_answers', models.IntegerField(db_column='num_answers')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_class_ans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionClassGenderAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_class_gender_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionClassGenderCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_class_gender_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionClassQuestionKeyAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_class_questionkey_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionClassQuestionKeyCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_class_questionkey_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionGroupGenderAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_questiongroup_gender_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionGroupGenderCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_questiongroup_gender_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionGroupQuestionKeyAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_questiongroup_questionkey_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionGroupQuestionKeyCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_questiongroup_questionkey_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionKeyAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_questionkey_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionKeyCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_questionkey_correctans_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionRespondentTypeAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_schools', models.IntegerField(db_column='num_schools')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
                ('num_children', models.IntegerField(db_column='num_children')),
                ('last_assessment', models.DateField(db_column='last_assessment')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_respondenttype_agg',
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionUserTypeAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(db_column='user_type', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('num_schools', models.IntegerField(db_column='num_schools')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
                ('num_children', models.IntegerField(db_column='num_children')),
                ('last_assessment', models.DateField(db_column='last_assessment')),
            ],
            options={
                'managed': False,
                'db_table': 'mvw_survey_institution_usertype_agg',
            },
        ),
        migrations.AlterModelTable(
            name='surveyquestiongroupquestionkeycorrectansagg',
            table='mvw_survey_questiongroup_questionkey_correctans_agg',
        ),
    ]
