# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-18 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_auto_20180117_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionimages',
            name='image',
            field=models.ImageField(upload_to='sys_images'),
        ),
    ]
