# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0036_auto_20180123_0923'),
        ('assessments', '0036_auto_20180118_1603'),
    ]

    operations = [
    ]
