# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0038_auto_20180123_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergroup_institution',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
