# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0039_auto_20180129_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='lang_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='image_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='lang_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
