# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0040_auto_20180208_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='image_required',
            field=models.NullBooleanField(default=False),
        ),
    ]
