# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0041_auto_20180209_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyBoundaryClassQuestionKeyGenderCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_boundary_class_questionkey_gender_correctans_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQuestionGroupQuestionKeyGenderCorrectAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_boundary_questiongroup_questionkey_gender_correctans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionClassQuestionKeyGenderCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(db_column='sg_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_institution_class_questionkey_gender_correctans_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionGroupQuestionKeyGenderCorrectAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('question_key', models.CharField(db_column='question_key', max_length=100)),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_institution_questiongroup_questionkey_gender_correctans',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='lang_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
