# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-27 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0043_surveyboundaryelectiontypecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroupKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, null=True)),
                ('max_score', models.IntegerField(null=True)),
                ('questiongroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.QuestionGroup')),
            ],
        ),
    ]
