# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-06 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0044_auto_20180226_1117'),
        ('assessments', '0044_auto_20180227_0923'),
    ]

    operations = [
    ]
