# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-07 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_respondenttype_state_code'),
        ('assessments', '0045_merge_20180306_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyUserTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Survey')),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.RespondentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='surveyusertypemapping',
            unique_together=set([('survey', 'usertype')]),
        ),
    ]
