# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-16 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0048_question_lang_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lang_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='lang_options',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.CharField(max_length=750, null=True),
        ),
    ]
