# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0051_questiongroup_default_respondent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='lang_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
