# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0052_surveydesclangblank_20180628_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='end_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='group_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='lang_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
