# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0053_blankallowedforassessmentsfields_20180628_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='lang_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
