# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-25 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0056_remove_partner_admin0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergroup_institution',
            name='group_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
