# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-06 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0057_auto_20180725_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='answergroup_student',
            name='entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='answergroup_studentgroup',
            name='entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
