# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-24 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0058_auto_20180806_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergroup_studentgroup',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='answergroup_studentgroup',
            name='group_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
