# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-23 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0058_auto_20180806_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('char_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LearningIndicator',
            fields=[
                ('char_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MicroConcept',
            fields=[
                ('char_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MicroConceptGroup',
            fields=[
                ('char_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInformationType',
            fields=[
                ('char_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLevel',
            fields=[
                ('char_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.Concept'),
        ),
        migrations.AddField(
            model_name='question',
            name='learning_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.LearningIndicator'),
        ),
        migrations.AddField(
            model_name='question',
            name='microconcept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.MicroConcept'),
        ),
        migrations.AddField(
            model_name='question',
            name='microconcept_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.MicroConceptGroup'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_info_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QuestionInformationType'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QuestionLevel'),
        ),
    ]
