# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0059_auto_20180823_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroupConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=50, null=True)),
                ('microconcept_group', models.CharField(max_length=50, null=True)),
                ('microconcept', models.CharField(max_length=50, null=True)),
                ('max_score', models.IntegerField(null=True)),
                ('questiongroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.QuestionGroup')),
            ],
        ),
    ]
