# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0060_questiongroupconcept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='char_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microconcept',
            name='char_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microconcept',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='microconceptgroup',
            name='char_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
