# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0062_auto_20180905_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroupconcept',
            name='microconcept',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
