# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-06 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0063_auto_20180905_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyBoundaryQDetailsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_boundary_qdetails_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQDetailsCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_boundary_qdetails_correctans_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQuestionGroupQDetailsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_boundary_questiongroup_qdetails_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyBoundaryQuestionGroupQDetailsCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_boundary_questiongroup_qdetails_correctans_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQDetailsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_institution_qdetails_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQDetailsCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_institution_qdetails_correctans_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionGroupQDetailsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_institution_questiongroup_qdetails_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyInstitutionQuestionGroupQDetailsCorrectAnsAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiongroup_name', models.CharField(db_column='questiongroup_name', max_length=100)),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('num_assessments', models.IntegerField(db_column='num_assessments')),
            ],
            options={
                'db_table': 'mvw_survey_institution_questiongroup_qdetails_correctans_agg',
                'managed': False,
            },
        ),
    ]
