# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-12 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0059_auto_20180824_1217'),
        ('assessments', '0064_surveyboundaryqdetailsagg_surveyboundaryqdetailscorrectansagg_surveyboundaryquestiongroupqdetailsagg'),
    ]

    operations = [
    ]
