# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-11 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0067_surveyeboundaryelectiontypecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInstitutionElectionTypeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearmonth', models.IntegerField(db_column='yearmonth')),
                ('electionboundary_count', models.IntegerField(db_column='electionboundary_count')),
            ],
            options={
                'db_table': 'mvw_survey_institution_electiontype_count',
                'managed': False,
            },
        ),
    ]
