# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-17 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0067_questiongroup_max_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField()),
                ('questiongroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.QuestionGroup')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyQuestionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Question')),
                ('questiongroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.QuestionGroup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='competencyquestionmap',
            unique_together=set([('questiongroup', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='competencyorder',
            unique_together=set([('key', 'questiongroup')]),
        ),
    ]
