# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0068_auto_20181017_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyquestionmap',
            name='max_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
