# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-17 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0068_surveyinstitutionelectiontypecount'),
        ('assessments', '0067_questiongroup_max_score'),
    ]

    operations = [
    ]
