# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-19 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0069_competencyquestionmap_max_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencyorder',
            old_name='order',
            new_name='sequence',
        ),
    ]
