# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-22 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0069_merge_20181017_1412'),
        ('assessments', '0070_auto_20181019_0917'),
    ]

    operations = [
    ]
