# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-05 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0071_merge_20181022_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningindicator',
            name='char_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
