# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('char_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('char_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('char_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionGender',
            fields=[
                ('char_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('char_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('char_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('char_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='institutiontype',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='institutiongender',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='grouptype',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='gender',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Status'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together=set([('year',)]),
        ),
    ]
