# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_religion_studentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentType',
            fields=[
                ('char_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
