# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0015_boundarystatecode'),
        ('common', '0003_respondenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondenttype',
            name='state_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boundary.BoundaryStateCode'),
        ),
    ]
