# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_respondenttype_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondenttype',
            name='active',
            field=models.ForeignKey(default='AC', on_delete=django.db.models.deletion.CASCADE, to='common.Status'),
        ),
    ]
