# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 07:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0002_auto_20170516_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('institution_type', models.CharField(choices=[('pre', 'Pre'), ('primary', 'Primary')], max_length=20)),
                ('dise_slug', models.CharField(max_length=300)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryNeighbours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Boundary')),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryType',
            fields=[
                ('char_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dise_slug', models.CharField(max_length=300)),
                ('elec_comm_code', models.IntegerField()),
                ('const_ward_name', models.CharField(max_length=300)),
                ('current_elected_rep', models.CharField(max_length=300)),
                ('const_ward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.BoundaryType')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionNeighbours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elect_boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.ElectionBoundary')),
                ('neighbour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_neighbour_neighbour', to='boundary.ElectionBoundary')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionParty',
            fields=[
                ('char_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('elect_boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.ElectionBoundary')),
                ('neighbour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_party_neighbour', to='boundary.ElectionBoundary')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dise_code', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('co-ed', 'Co-Ed')], max_length=10)),
                ('institution_type', models.CharField(choices=[('pre', 'Pre'), ('primary', 'Primary')], max_length=20)),
                ('year_established', models.CharField(blank=True, max_length=5, null=True)),
                ('rural_urban', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=1000)),
                ('area', models.CharField(max_length=1000)),
                ('village', models.CharField(max_length=1000)),
                ('landmark', models.CharField(blank=True, max_length=1000, null=True)),
                ('instidentification', models.CharField(blank=True, max_length=1000, null=True)),
                ('instidentification2', models.CharField(blank=True, max_length=1000, null=True)),
                ('route_information', models.CharField(blank=True, max_length=1000, null=True)),
                ('coord', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('admin0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_admin0', to='boundary.Boundary')),
                ('admin1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_admin1', to='boundary.Boundary')),
                ('admin2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_admin2', to='boundary.Boundary')),
                ('admin3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_admin3', to='boundary.Boundary')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.InstitutionCategory')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_gp', to='boundary.ElectionBoundary')),
                ('last_verified_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.AcademicYear')),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Management')),
                ('mla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_mla', to='boundary.ElectionBoundary')),
                ('moi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Language')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_mp', to='boundary.ElectionBoundary')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.PinCode')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Status')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_ward', to='boundary.ElectionBoundary')),
            ],
        ),
        migrations.AddField(
            model_name='electionboundary',
            name='current_elected_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.ElectionParty'),
        ),
        migrations.AddField(
            model_name='electionboundary',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.ElectionBoundary'),
        ),
        migrations.AddField(
            model_name='electionboundary',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Status'),
        ),
        migrations.AddField(
            model_name='boundaryneighbours',
            name='neighbour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.ElectionBoundary'),
        ),
        migrations.AddField(
            model_name='boundary',
            name='boundary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.BoundaryType'),
        ),
        migrations.AddField(
            model_name='boundary',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Boundary'),
        ),
        migrations.AddField(
            model_name='boundary',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Status'),
        ),
    ]
