# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171222_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no1',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
