# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-13 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0011_pregroupuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pregroupuser',
            unique_together=set([('mobile_no', 'source', 'group')]),
        ),
    ]
