# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180613_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboundary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userboundaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
