# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-09 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180808_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboundary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userboundaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
