# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-14 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180809_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordless_login_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
