# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-14 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_passwordless_login_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwordless_login_token',
            new_name='secure_login_token',
        ),
    ]
