insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24909,'Venkatarathnamma','female','36273','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24910,'Venkataramanappa','male','35952','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24911,'Kavitha C','female','35952','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24912,'Krishnappa','male','35953','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24913,'Rajashekar','male','35953','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24914,'Chalina','female','35935','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24915,'Gayathri','female','35935','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24916,'Sayeedunnisa','female','35932','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24917,'Sunanda Bargundi','female','35932','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24918,'Roshan Ara','female','35932','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24919,'Sumaiya begum','female','35932','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24920,'R Manjula','female','35931','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24921,'K radhika','female','35931','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24922,'Ramanamma','female','35934','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24923,'Muniyappa','male','35934','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24924,'Padmavathi hegde','female','35941','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24925,'Govindappa MS','male','35941','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24926,'Narayana Gowda V','male','35941','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24927,'Ramadevi DC','female','35941','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24928,'Rajshekar','male','35949','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24929,'Dhanalakshmi','female','35949','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24930,'Manjula BT','female','35940','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24931,'Mallika hegde','female','35940','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24932,'Jayamma','female','35933','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24933,'Nahida Amrin','female','35933','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24934,'Mahalingam','male','35942','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24935,'Yashodhamma','female','35942','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24936,'D K Nagaraj','male','35936','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24937,'Mangala N bhat','female','35936','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24938,'B Maruthesh','male','35936','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24939,'F R Farnandis','female','35936','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24940,'Vanitha GS','female','35936','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24941,'Sudhamani DM','female','35936','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24942,'Subramani KC','male','35936','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24943,'Rashmi S','female','35936','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24944,'B Gopal nayak','male','35939','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24945,'G Narayanaswamy','male','35939','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24946,'Narayanaswamy','male','35939','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24947,'Ashok Biradal','male','35939','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24948,'V Manjula','female','35937','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24949,'M Narayanappa','male','35937','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24950,'Gopalappa M','male','35938','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24951,'Venugopal','male','35938','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24952,'Santhesh S V','male','36063','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24953,'Radhamma','female','36206','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24954,'Sunanda R','female','36206','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24955,'Hema R','female','36206','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24956,'Jaimala','female','36206','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24957,'Mariswami','male','35945','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24958,'Manjunatha','male','35945','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24959,'Panduranga','male','35943','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24960,'Ganesh','male','35943','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24961,'Gowri K bhatt','female','36224','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24962,'Ramadevi K N','female','36224','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24963,'Ambujakshi','female','36224','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24964,'Umabhatt','female','36224','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24965,'Dilshad farzana','female','36224','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24966,'Mallikarjuna V','male','36220','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24967,'Janardhan','male','36220','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24968,'Munilakshmamma','female','36220','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24969,'Ramanjinappa V M','male','36220','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24970,'Rehana bhanu','female','36058','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24971,'Poornima','female','36058','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24972,'Suvarna','female','36200','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24973,'Savithri balla','female','36200','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24974,'Chethana','female','36200','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24975,'Rashmi R','female','36200','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24976,'Ramesh','female','36213','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24977,'Usha','female','36213','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24978,'Venkataramanappa','male','36193','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24979,'Kausthuba','female','36193','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24980,'Saraswathi','female','36193','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24981,'Lakshmidevi','female','36210','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24982,'Nagaveni','female','36210','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24983,'Chndrakantha','female','36223','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24984,'Mangala mary','female','36223','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24985,'Leelavathi','female','36222','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24986,'A Y Kanthi','female','36222','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24987,'Rama K','female','36222','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24988,'Pushpakshi G','female','36222','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24989,'Jayalakshmi','female','35963','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24990,'Banashankavamma RS','female','35966','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24991,'Nagarathana KD','female','35966','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24992,'Puneetha R','female','35966','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24993,'Sowmya TG','female','35966','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24994,'Manjula TD','female','35966','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24995,'KS Karuna','female','35957','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24996,'A Farzana','female','35957','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24997,'R Nirmala','female','35957','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24998,'K V Lakshmamma','female','35957','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (24999,'Rizwana Taj','female','36089','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25000,'Amreen Taj','female','36089','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25001,'Kamalamma V','female','36089','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25002,'Salama A','female','36089','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25003,'Farzana Khnum','female','36089','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25004,'Shaista Kousar','female','36089','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25005,'Nagarathna','female','42651','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25006,'Meenakshi','female','42651','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25007,'Allahbakesh','male','36297','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25008,'Shahanaz begum','female','36297','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25009,'Mubeen taj','female','36297','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25010,'Reshma M','female','36297','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25011,'Shashikala','female','36297','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25012,'Venkatesh HK','male','36751','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25013,'Pankaja A','female','36751','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25014,'Prabhakara raj','male','35970','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25015,'Harish P.L','male','35970','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25016,'Gowri MK','female','35969','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25017,'Rabackal Selva Kumar','female','35969','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25018,'Leelavathi','female','35969','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25019,'Kavitha','female','35969','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25020,'Zaheer Pasha','male','36091','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25021,'Umme Attika','female','36091','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25022,'Sadiya Sultana','female','36091','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25023,'Sattya Narayanappa','male','36107','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25024,'Bharathi N','female','36107','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25025,'Kamala Bhat','female','35971','kan',1,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25026,'Chinamma','female','35971','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25027,'Bhagyamma T','female','11582','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25028,'Prashanth Kumar','male','11548','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25029,'Subramani','male','11567','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25030,'Tejasvi','female','11549','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25031,'Ambika','female','11560','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25032,'Nagarathna','female','11545','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25033,'Manojamma','female','11545','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25034,'Manjunatha','male','11539','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25035,'Vedavathi','female','11581','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25036,'Varalaskhmi','female','11550','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25037,'Naveen','male','11552','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25038,'Venkateshappa','male','11550','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25039,'N R Adinarayana','male','11579','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25040,'K V Manjunath','male','11571','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25041,'S Narayanaswamy','male','11579','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25042,'Jayaprakash','male','11551','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25043,'Srinivas N','male','43550','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25044,'Vijay kumar','male','11573','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25045,'S S Prakash','male','11563','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25046,'Anil Mahajana Shettar','male','11569','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25047,'Shalini','female','11576','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25048,'Ramanna R','male','43549','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25049,'Venkatarathna','male','11564','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25050,'Lakshmi Narayana','female','11578','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25051,'Manjunath','male','11575','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25052,'Shalini','female','11576','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25053,'Manojamma','female','11542','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25054,'Kavitha','female','45352','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25055,'Rohini K','female','43529','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25056,'Chowdappa N','male','11537','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25057,'Sheela M','female','11546','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25058,'Nagarathna','female','11530','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25059,'Swetha','female','43535','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25060,'Sathish Babu','male','43533','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25061,'Krishnappa','male','43531','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25062,'Lakshmi Devamma','female','43528','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25063,'Ambika','female','11536','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25064,'Purushotham','male','43534','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25065,'Renukamma','female','43530','kan',2,'AC');
insert into schools_staff (id,first_name,gender_id,institution_id,mt_id,staff_type_id,status_id) values (25066,'Neola Sharan','female','32692','kan',2,'AC');
