# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicdata',
            old_name='yeur_estd',
            new_name='year_estd',
        ),
    ]
