# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-25 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dise', '0004_auto_20170718_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='state_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
