insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11072','angul','angul-angul','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11073','angul mpl','angul-angul mpl','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11074','athamallik','angul-athamallik','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11075','athamallik nac','angul-athamallik nac','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11076','banarpal','angul-banarpal','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11077','chhendipada','angul-chhendipada','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11078','kaniha','angul-kaniha','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11079','kishorenagar','angul-kishorenagar','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11080','pallahara','angul-pallahara','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11081','talcher','angul-talcher','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11082','talcher mpl','angul-talcher mpl','SB','11042','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11083','bahanaga','balasore-bahanaga','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11084','balasore mpl','balasore-balasore mpl','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11085','baliapal','balasore-baliapal','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11086','basta','balasore-basta','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11087','bhogarai','balasore-bhogarai','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11088','jaleswar','balasore-jaleswar','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11089','jaleswar nac','balasore-jaleswar nac','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11090','khaira','balasore-khaira','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11091','nilgiri','balasore-nilgiri','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11092','nilgiri nac','balasore-nilgiri nac','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11093','oupada','balasore-oupada','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11094','remuna','balasore-remuna','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11095','sadar','balasore-sadar','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11096','simulia','balasore-simulia','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11097','soro','balasore-soro','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11098','soro nac','balasore-soro nac','SB','11043','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11099','ambabhona','bargarh-ambabhona','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11100','attabira','bargarh-attabira','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11101','bargarh','bargarh-bargarh','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11102','bargarh mpl','bargarh-bargarh mpl','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11103','barpali','bargarh-barpali','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11104','barpali nac','bargarh-barpali nac','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11105','bhatali','bargarh-bhatali','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11106','bheden','bargarh-bheden','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11107','bijepur','bargarh-bijepur','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11108','gaisilet','bargarh-gaisilet','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11109','jharbandh','bargarh-jharbandh','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11110','padampur nac','bargarh-padampur nac','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11111','paikmal','bargarh-paikmal','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11112','rajborasambar','bargarh-rajborasambar','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11113','sohella','bargarh-sohella','SB','11044','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11114','basudevpur','bhadrak-basudevpur','SB','11045','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11115','basudevpur mpl','bhadrak-basudevpur mpl','SB','11045','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11116','bhadrak','bhadrak-bhadrak','SB','11045','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11117','bhadrak mpl','bhadrak-bhadrak mpl','SB','11045','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11118','bhandaripokhari','bhadrak-bhandaripokhari','SB','11045','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11119','bonth','bhadrak-bonth','SB','11045','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11120','chandabali','bhadrak-chandabali','SB','11045','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11121','dhamnagar','bhadrak-dhamnagar','SB','11045','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11122','tihidi','bhadrak-tihidi','SB','11045','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11123','agalpur','bolangir-agalpur','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11124','balangir','bolangir-balangir','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11125','balangir mpl','bolangir-balangir mpl','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11126','bangomunda','bolangir-bangomunda','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11127','belpada','bolangir-belpada','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11128','deogaon','bolangir-deogaon','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11129','gudvela','bolangir-gudvela','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11130','kantabanji nac','bolangir-kantabanji nac','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11131','khaprakhol','bolangir-khaprakhol','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11132','loisingha','bolangir-loisingha','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11133','muribahal','bolangir-muribahal','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11134','patnagarh','bolangir-patnagarh','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11135','patnagarh nac','bolangir-patnagarh nac','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11136','puintala','bolangir-puintala','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11137','saintala','bolangir-saintala','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11138','titilagarh','bolangir-titilagarh','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11139','titilagarh nac','bolangir-titilagarh nac','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11140','turekela','bolangir-turekela','SB','11046','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11141','boudh','boudh-boudh','SB','11047','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11142','boudh nac','boudh-boudh nac','SB','11047','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11143','harabhanga','boudh-harabhanga','SB','11047','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11144','kantamal','boudh-kantamal','SB','11047','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11145','arc charbatia','cuttack-arc charbatia','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11146','athagarh nac','cuttack-athagarh nac','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11147','athgarh','cuttack-athgarh','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11148','banki','cuttack-banki','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11149','banki nac','cuttack-banki nac','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11150','baramba','cuttack-baramba','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11151','baranga','cuttack-baranga','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11152','choudwar mpl','cuttack-choudwar mpl','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11153','cuttack mc','cuttack-cuttack mc','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11154','cuttack sadar','cuttack-cuttack sadar','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11155','dompara','cuttack-dompara','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11156','kantapara','cuttack-kantapara','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11157','mahanga','cuttack-mahanga','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11158','narsinghpur','cuttack-narsinghpur','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11159','niali','cuttack-niali','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11160','nischintakoili','cuttack-nischintakoili','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11161','salipur','cuttack-salipur','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11162','tangi','cuttack-tangi','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11163','tigiria','cuttack-tigiria','SB','11048','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11164','barkote','deogarh-barkote','SB','11049','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11165','deogarh mpl','deogarh-deogarh mpl','SB','11049','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11166','reamal','deogarh-reamal','SB','11049','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11167','tileibani','deogarh-tileibani','SB','11049','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11168','bhuban','dhenkanal-bhuban','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11169','bhuban nac','dhenkanal-bhuban nac','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11170','dhenkanal mpl','dhenkanal-dhenkanal mpl','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11171','dhenkanal sadar','dhenkanal-dhenkanal sadar','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11172','gondia','dhenkanal-gondia','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11173','hindol','dhenkanal-hindol','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11174','hindol nac','dhenkanal-hindol nac','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11175','kamakhyanagar','dhenkanal-kamakhyanagar','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11176','kamakhyanagar nac','dhenkanal-kamakhyanagar nac','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11177','kankadahad','dhenkanal-kankadahad','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11178','odapada','dhenkanal-odapada','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11179','parjang','dhenkanal-parjang','SB','11050','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11180','gosani','gajapati-gosani','SB','11051','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11181','gumma','gajapati-gumma','SB','11051','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11182','kashinagar','gajapati-kashinagar','SB','11051','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11183','kashinagar(nac)','gajapati-kashinagar(nac)','SB','11051','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11184','mohana','gajapati-mohana','SB','11051','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11185','nuagada','gajapati-nuagada','SB','11051','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11186','paralakhemundi (mpl)','gajapati-paralakhemundi (mpl)','SB','11051','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11187','r udayagiri','gajapati-r udayagiri','SB','11051','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11188','rayagada','gajapati-rayagada','SB','11051','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11189','aska','ganjam-aska','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11190','aska nac','ganjam-aska nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11191','beguniapada','ganjam-beguniapada','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11192','bellaguntha','ganjam-bellaguntha','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11193','bellaguntha nac','ganjam-bellaguntha nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11194','berhampur mpl','ganjam-berhampur mpl','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11195','bhanjanagar','ganjam-bhanjanagar','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11196','bhanjanagar nac','ganjam-bhanjanagar nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11197','buguda','ganjam-buguda','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11198','buguda nac','ganjam-buguda nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11199','chatrapur','ganjam-chatrapur','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11200','chatrapur nac','ganjam-chatrapur nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11201','chikiti','ganjam-chikiti','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11202','chikiti nac','ganjam-chikiti nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11203','dharakote','ganjam-dharakote','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11204','digapahandi','ganjam-digapahandi','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11205','digapahandi nac','ganjam-digapahandi nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11206','ganjam','ganjam-ganjam','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11207','ganjam nac','ganjam-ganjam nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11208','gopalapur nac','ganjam-gopalapur nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11209','hinjilicut','ganjam-hinjilicut','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11210','hinjilicut nac','ganjam-hinjilicut nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11211','jaganathprasad','ganjam-jaganathprasad','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11212','kabisuryanagar','ganjam-kabisuryanagar','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11213','kabisuryanagar nac','ganjam-kabisuryanagar nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11214','khallikote','ganjam-khallikote','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11215','khallikote nac','ganjam-khallikote nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11216','kodala nac','ganjam-kodala nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11217','kukudakhandi','ganjam-kukudakhandi','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11218','patrapur','ganjam-patrapur','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11219','polasara','ganjam-polasara','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11220','polasara nac','ganjam-polasara nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11221','purusotampur','ganjam-purusotampur','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11222','purusotampur nac','ganjam-purusotampur nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11223','rambha nac','ganjam-rambha nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11224','rangeilunda','ganjam-rangeilunda','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11225','sanakhemundi','ganjam-sanakhemundi','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11226','sheragada','ganjam-sheragada','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11227','surada','ganjam-surada','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11228','surada nac','ganjam-surada nac','SB','11052','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11229','balikuda','jagatsinghpur-balikuda','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11230','biridi','jagatsinghpur-biridi','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11231','cuttack part (extra block)','jagatsinghpur-cuttack part (extra block)','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11232','erasama','jagatsinghpur-erasama','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11233','jagatsinghpur','jagatsinghpur-jagatsinghpur','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11234','jagatsinghpur mplt','jagatsinghpur-jagatsinghpur mplt','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11235','kujang','jagatsinghpur-kujang','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11236','naugaon','jagatsinghpur-naugaon','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11237','paradeep mplt','jagatsinghpur-paradeep mplt','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11238','raghunathpur','jagatsinghpur-raghunathpur','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11239','tirtol','jagatsinghpur-tirtol','SB','11053','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11240','barchana','jajpur-barchana','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11241','bari','jajpur-bari','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11242','binjharpur','jajpur-binjharpur','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11243','danagadi','jajpur-danagadi','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11244','dasarathpur','jajpur-dasarathpur','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11245','dharmasala','jajpur-dharmasala','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11246','jajpur','jajpur-jajpur','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11247','jajpur mpl','jajpur-jajpur mpl','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11248','korai','jajpur-korai','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11249','rasulpur','jajpur-rasulpur','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11250','sukinda','jajpur-sukinda','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11251','vyasanagar mpl','jajpur-vyasanagar mpl','SB','11054','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11252','belpahar mpl','jharsuguda-belpahar mpl','SB','11055','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11253','brajarajnagar mpl','jharsuguda-brajarajnagar mpl','SB','11055','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11254','jharsuguda','jharsuguda-jharsuguda','SB','11055','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11255','jharsuguda mpl','jharsuguda-jharsuguda mpl','SB','11055','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11256','kirmira','jharsuguda-kirmira','SB','11055','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11257','kolabira','jharsuguda-kolabira','SB','11055','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11258','laikera','jharsuguda-laikera','SB','11055','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11259','lakhanpur','jharsuguda-lakhanpur','SB','11055','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11260','bhawanipatna','kalahandi-bhawanipatna','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11261','bhawanipatna mpl','kalahandi-bhawanipatna mpl','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11262','dharamgarh','kalahandi-dharamgarh','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11263','golamunda','kalahandi-golamunda','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11264','jaipatna','kalahandi-jaipatna','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11265','junagarh','kalahandi-junagarh','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11266','junagarh nac','kalahandi-junagarh nac','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11267','kalampur','kalahandi-kalampur','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11268','karlamunda','kalahandi-karlamunda','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11269','kesinga','kalahandi-kesinga','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11270','kesinga nac','kalahandi-kesinga nac','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11271','koksara','kalahandi-koksara','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11272','lanjigarh','kalahandi-lanjigarh','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11273','m rampur','kalahandi-m rampur','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11274','narla','kalahandi-narla','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11275','th rampur','kalahandi-th rampur','SB','11056','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11276','balliguda','kandhamal-balliguda','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11277','chakapad','kandhamal-chakapad','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11278','daringbadi','kandhamal-daringbadi','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11279','g udayagiri','kandhamal-g udayagiri','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11280','g udayagiri nac','kandhamal-g udayagiri nac','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11281','k nuagam','kandhamal-k nuagam','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11282','khajuripada','kandhamal-khajuripada','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11283','kotaghar','kandhamal-kotaghar','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11284','phiringia','kandhamal-phiringia','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11285','phulbani','kandhamal-phulbani','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11286','phulbani mpl ','kandhamal-phulbani mpl ','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11287','raikia','kandhamal-raikia','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11288','tikabali','kandhamal-tikabali','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11289','tumudibandha','kandhamal-tumudibandha','SB','11057','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11290','aul','kendrapara-aul','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11291','derabish','kendrapara-derabish','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11292','garadapur','kendrapara-garadapur','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11293','kendrapara','kendrapara-kendrapara','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11294','kendrapara mpl','kendrapara-kendrapara mpl','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11295','mahakalpara','kendrapara-mahakalpara','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11296','marshaghai','kendrapara-marshaghai','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11297','pattamundai','kendrapara-pattamundai','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11298','pattamundai nac','kendrapara-pattamundai nac','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11299','rajkanika','kendrapara-rajkanika','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11300','rajnagar','kendrapara-rajnagar','SB','11058','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11301','anandapur','keonjhar-anandapur','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11302','anandapur mpl','keonjhar-anandapur mpl','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11303','banspal','keonjhar-banspal','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11304','barbil mpl','keonjhar-barbil mpl','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11305','champua','keonjhar-champua','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11306','ghasipura','keonjhar-ghasipura','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11307','ghatagaon','keonjhar-ghatagaon','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11308','harichandanpur','keonjhar-harichandanpur','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11309','hatadihi','keonjhar-hatadihi','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11310','jhumpura','keonjhar-jhumpura','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11311','joda','keonjhar-joda','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11312','joda mpl','keonjhar-joda mpl','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11313','keonjhar','keonjhar-keonjhar','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11314','keonjhar mpl','keonjhar-keonjhar mpl','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11315','patna','keonjhar-patna','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11316','saharapada','keonjhar-saharapada','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11317','telkoi','keonjhar-telkoi','SB','11059','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11318','balianta','khordha-balianta','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11319','balipatna','khordha-balipatna','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11320','balugaon nac','khordha-balugaon nac','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11321','banapur','khordha-banapur','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11322','banapur nac','khordha-banapur nac','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11323','begunia','khordha-begunia','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11324','bhubaneswar','khordha-bhubaneswar','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11325','bhubaneswar mc','khordha-bhubaneswar mc','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11326','bolgarh','khordha-bolgarh','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11327','chilika','khordha-chilika','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11328','jatni','khordha-jatni','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11329','jatni mpl','khordha-jatni mpl','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11330','khordha','khordha-khordha','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11331','khordha mpl','khordha-khordha mpl','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11332','tangi','khordha-tangi','SB','11060','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11333','bandhugam','koraput-bandhugam','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11334','boipariguda','koraput-boipariguda','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11335','borigumma','koraput-borigumma','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11336','dasmantpur','koraput-dasmantpur','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11337','jeypore','koraput-jeypore','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11338','jeypore mpl','koraput-jeypore mpl','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11339','koraput','koraput-koraput','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11340','koraput nac','koraput-koraput nac','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11341','kotpad','koraput-kotpad','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11342','kotpad nac','koraput-kotpad nac','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11343','kundra','koraput-kundra','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11344','lamtaput','koraput-lamtaput','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11345','laxmipur','koraput-laxmipur','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11346','nandapur','koraput-nandapur','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11347','narayanapatna','koraput-narayanapatna','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11348','pottangi','koraput-pottangi','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11349','semiliguda','koraput-semiliguda','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11350','sunabeda nac','koraput-sunabeda nac','SB','11061','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11351','balimela nac','malkangiri-balimela nac','SB','11062','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11352','kalimela','malkangiri-kalimela','SB','11062','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11353','khairput','malkangiri-khairput','SB','11062','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11354','korukonda','malkangiri-korukonda','SB','11062','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11355','kudumulugumma','malkangiri-kudumulugumma','SB','11062','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11356','malkangiri','malkangiri-malkangiri','SB','11062','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11357','malkangiri nac','malkangiri-malkangiri nac','SB','11062','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11358','mathili','malkangiri-mathili','SB','11062','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11359','podia','malkangiri-podia','SB','11062','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11360','bahalda','mayurbhanj-bahalda','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11361','bangriposi','mayurbhanj-bangriposi','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11362','barasahi','mayurbhanj-barasahi','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11363','baripada','mayurbhanj-baripada','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11364','baripada mpl','mayurbhanj-baripada mpl','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11365','betnoti','mayurbhanj-betnoti','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11366','bijatola','mayurbhanj-bijatola','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11367','bisoi','mayurbhanj-bisoi','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11368','g b nagar','mayurbhanj-g b nagar','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11369','jamda','mayurbhanj-jamda','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11370','jashipur','mayurbhanj-jashipur','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11371','kaptipada','mayurbhanj-kaptipada','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11372','karanjia','mayurbhanj-karanjia','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11373','karanjia nac','mayurbhanj-karanjia nac','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11374','khunta','mayurbhanj-khunta','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11375','kuliana','mayurbhanj-kuliana','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11376','kusumi','mayurbhanj-kusumi','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11377','morada','mayurbhanj-morada','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11378','rairangpur','mayurbhanj-rairangpur','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11379','rairangpur nac','mayurbhanj-rairangpur nac','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11380','raruan','mayurbhanj-raruan','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11381','rasgovindpur','mayurbhanj-rasgovindpur','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11382','saraskana','mayurbhanj-saraskana','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11383','shamakhunta','mayurbhanj-shamakhunta','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11384','sukruli','mayurbhanj-sukruli','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11385','suliapada','mayurbhanj-suliapada','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11386','thakurmunda','mayurbhanj-thakurmunda','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11387','tiring','mayurbhanj-tiring','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11388','udala','mayurbhanj-udala','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11389','udala nac','mayurbhanj-udala nac','SB','11063','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11390','chandahandi','nabarangpur-chandahandi','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11391','dabugam','nabarangpur-dabugam','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11392','jharigam','nabarangpur-jharigam','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11393','kosagumuda','nabarangpur-kosagumuda','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11394','nabarangpur','nabarangpur-nabarangpur','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11395','nabarangpur mpl','nabarangpur-nabarangpur mpl','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11396','nandahandi','nabarangpur-nandahandi','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11397','papadahandi','nabarangpur-papadahandi','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11398','raighar','nabarangpur-raighar','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11399','tentulikhunti','nabarangpur-tentulikhunti','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11400','umerkote','nabarangpur-umerkote','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11401','umerkote nac','nabarangpur-umerkote nac','SB','11064','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11402','bhapur','nayagarh-bhapur','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11403','daspalla','nayagarh-daspalla','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11404','gania','nayagarh-gania','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11405','khandapada','nayagarh-khandapada','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11406','khandapada nac','nayagarh-khandapada nac','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11407','nayagarh','nayagarh-nayagarh','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11408','nayagarh nac','nayagarh-nayagarh nac','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11409','nuagaon','nayagarh-nuagaon','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11410','odagaon','nayagarh-odagaon','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11411','ranpur','nayagarh-ranpur','SB','11065','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11412','boden','nuapada-boden','SB','11066','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11413','khariar','nuapada-khariar','SB','11066','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11414','khariar nac','nuapada-khariar nac','SB','11066','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11415','khariar road nac','nuapada-khariar road nac','SB','11066','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11416','komna','nuapada-komna','SB','11066','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11417','nuapada','nuapada-nuapada','SB','11066','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11418','sinapali','nuapada-sinapali','SB','11066','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11419','astarang','puri-astarang','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11420','brahmagiri','puri-brahmagiri','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11421','delang','puri-delang','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11422','gop','puri-gop','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11423','kakatpur','puri-kakatpur','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11424','kanas','puri-kanas','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11425','konark nac','puri-konark nac','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11426','krushnaprasad','puri-krushnaprasad','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11427','nimapara','puri-nimapara','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11428','nimapara nac','puri-nimapara nac','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11429','pipili','puri-pipili','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11430','pipli nac','puri-pipli nac','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11431','puri mpl','puri-puri mpl','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11432','puri sadar','puri-puri sadar','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11433','satyabadi','puri-satyabadi','SB','11067','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11434','bissamcuttack','rayagada-bissamcuttack','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11435','chandrapur','rayagada-chandrapur','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11436','gudari','rayagada-gudari','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11437','gudari nac','rayagada-gudari nac','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11438','gunupur','rayagada-gunupur','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11439','gunupur nac','rayagada-gunupur nac','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11440','k singpur','rayagada-k singpur','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11441','kasipur','rayagada-kasipur','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11442','kolnara','rayagada-kolnara','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11443','muniguda','rayagada-muniguda','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11444','padampur','rayagada-padampur','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11445','ramanaguda','rayagada-ramanaguda','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11446','rayagada','rayagada-rayagada','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11447','rayagada mplt','rayagada-rayagada mplt','SB','11068','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11448','bamra','sambalpur-bamra','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11449','burla nac','sambalpur-burla nac','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11450','dhankauda','sambalpur-dhankauda','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11451','hirakud nac','sambalpur-hirakud nac','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11452','jamankira','sambalpur-jamankira','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11453','jujumura','sambalpur-jujumura','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11454','kuchinda','sambalpur-kuchinda','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11455','kuchinda nac','sambalpur-kuchinda nac','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11456','maneswar','sambalpur-maneswar','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11457','naktideul','sambalpur-naktideul','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11458','rairakhol','sambalpur-rairakhol','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11459','rairakhol nac','sambalpur-rairakhol nac','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11460','rengali','sambalpur-rengali','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11461','sambalpur mpl','sambalpur-sambalpur mpl','SB','11069','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11462','binka','sonepur-binka','SB','11070','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11463','binka nac','sonepur-binka nac','SB','11070','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11464','birmaharajpur','sonepur-birmaharajpur','SB','11070','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11465','dunguripali','sonepur-dunguripali','SB','11070','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11466','sonepur','sonepur-sonepur','SB','11070','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11467','sonepur mpl','sonepur-sonepur mpl','SB','11070','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11468','tarva','sonepur-tarva','SB','11070','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11469','tarva nac','sonepur-tarva nac','SB','11070','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11470','ullunda','sonepur-ullunda','SB','11070','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11471','balisankara','sundergarh-balisankara','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11472','bargaon','sundergarh-bargaon','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11473','biramitrapur mpl','sundergarh-biramitrapur mpl','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11474','bisra','sundergarh-bisra','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11475','bonai','sundergarh-bonai','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11476','gurundia','sundergarh-gurundia','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11477','hemgiri','sundergarh-hemgiri','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11478','koira','sundergarh-koira','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11479','kuarmunda','sundergarh-kuarmunda','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11480','kutra','sundergarh-kutra','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11481','lahunipara','sundergarh-lahunipara','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11482','lathikata','sundergarh-lathikata','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11483','lephripara','sundergarh-lephripara','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11484','nuagaon','sundergarh-nuagaon','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11485','rajgangpur','sundergarh-rajgangpur','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11486','rajgangpur mpl','sundergarh-rajgangpur mpl','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11487','rourkela mpl','sundergarh-rourkela mpl','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11488','subdega','sundergarh-subdega','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11489','sundargarh','sundergarh-sundargarh','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11490','sundargarh mpl','sundergarh-sundargarh mpl','SB','11071','AC','primary');
insert into boundary_boundary (id,name,dise_slug,boundary_type_id,parent_id,status_id,type_id) values ('11491','tangarpali','sundergarh-tangarpali','SB','11071','AC','primary');
