# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0003_auto_20170703_2237'),
        ('common', '0002_religion_studentcategory'),
        ('schools', '0002_auto_20170628_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('num', models.IntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.AcademicYear')),
            ],
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='area',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='dise_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.PinCode'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='village',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.StudentCategory'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Religion'),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set([('name', 'admin3')]),
        ),
        migrations.DeleteModel(
            name='StudentCategory',
        ),
        migrations.DeleteModel(
            name='StudentReligion',
        ),
        migrations.AddField(
            model_name='institutionaggregation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.StudentCategory'),
        ),
        migrations.AddField(
            model_name='institutionaggregation',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Gender'),
        ),
        migrations.AddField(
            model_name='institutionaggregation',
            name='moi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst_agg_moi', to='common.Language'),
        ),
        migrations.AddField(
            model_name='institutionaggregation',
            name='mt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst_agg_mt', to='common.Language'),
        ),
        migrations.AddField(
            model_name='institutionaggregation',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Religion'),
        ),
        migrations.AddField(
            model_name='institutionaggregation',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Institution'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionaggregation',
            unique_together=set([('id', 'academic_year', 'gender', 'moi', 'mt', 'religion', 'category')]),
        ),
    ]
