# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_religion_studentcategory'),
        ('schools', '0003_auto_20170703_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='institutionaggregation',
            old_name='sid',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='moi',
        ),
        migrations.AddField(
            model_name='institutionlanguage',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Institution'),
        ),
        migrations.AddField(
            model_name='institutionlanguage',
            name='moi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionlanguage',
            unique_together=set([('institution', 'moi')]),
        ),
    ]
