# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20170704_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.InstitutionGender'),
        ),
    ]
