# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0005_merge_20170705_1012'),
        ('schools', '0005_auto_20170705_0925'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set([('name', 'dise_code', 'admin3')]),
        ),
    ]
