# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20170705_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionaggregation',
            options={'managed': False},
        ),
    ]
