# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20170724_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionClassYearStuCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, db_column=b'num', null=True)),
            ],
            options={
                'db_table': 'mvw_institution_class_year_stucount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionStuGenderCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_boys', models.IntegerField(blank=True, db_column=b'num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column=b'num_girls', null=True)),
            ],
            options={
                'db_table': 'mvw_institution_stu_gender_count',
                'managed': False,
            },
        ),
    ]
