# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_institutionclassyearstucount_institutionstugendercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(related_name='studentgroups', through='schools.StudentStudentGroupRelation', to='schools.Student'),
        ),
    ]
