# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dise', '0004_auto_20170718_1439'),
        ('schools', '0010_studentgroup_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='dise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dise.BasicData'),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='institution',
            name='dise_code',
        ),
    ]
