# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dise', '0004_auto_20170718_1439'),
        ('boundary', '0011_electionboundary_geom'),
        ('schools', '0011_auto_20170912_1117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set([('name', 'dise', 'admin3')]),
        ),
    ]
