# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_auto_20171027_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.ForeignKey(default='AC', on_delete=django.db.models.deletion.CASCADE, to='common.Status'),
        ),
    ]
