# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20171102_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionlanguage',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_languages', to='schools.Institution'),
        ),
    ]
