# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 04:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_auto_20171110_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
