# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_auto_20171110_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='staff',
            field=models.ManyToManyField(through='schools.StaffStudentGroupRelation', to='schools.Staff'),
        ),
    ]
