# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20180111_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='staff',
            field=models.ManyToManyField(through='schools.StaffStudentGroupRelation', to='schools.Staff'),
        ),
    ]
