# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20180111_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'permissions': (('crud_student_class_staff', 'CRUD Student Class and Staff'),)},
        ),
    ]
