# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-22 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_institution_permissions_20180503_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(default='male', on_delete=django.db.models.deletion.CASCADE, to='common.Gender'),
        ),
    ]
