# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-03 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20180622_1504'),
        ('schools', '0017_studentgroup_staff'),
    ]

    operations = [
    ]
