# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-16 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='downloaded_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='visited_at',
            field=models.DateField(null=True),
        ),
    ]
