# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-17 06:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20180516_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=50)),
                ('contacts', models.CharField(max_length=50)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('report_type', models.CharField(max_length=50)),
            ],
        ),
    ]
