# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 04:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_sending_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
