# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-08 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reports_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='recipient',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='report_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
