# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-19 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180608_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
