# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_tracking_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
