# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-25 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_tracking_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sending_Information',
        ),
    ]
