# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-19 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0021_boundarystatecode_language'),
        ('reports', '0008_delete_sending_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='state',
            field=models.ForeignKey(db_column='state_id', default=reports.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='boundary.Boundary'),
        ),
    ]
