# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reports_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPStudentScoreGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_students', models.IntegerField(db_column='num_students')),
                ('cat_a', models.IntegerField(db_column='cat_a')),
                ('cat_b', models.IntegerField(db_column='cat_b')),
                ('cat_c', models.IntegerField(db_column='cat_c')),
                ('cat_d', models.IntegerField(db_column='cat_d')),
            ],
            options={
                'db_table': 'mvw_survey_eboundary_answers_agg',
                'managed': False,
            },
        ),
    ]
