psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_BENGALURU_RURAL-January_2017-18.sql   
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_CHIKKABALLAPURA-November_2017-18.sql
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_BENGALURU_RURAL-March_2017-18.sql     
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_CHITRADURGA-March_2017-18.sql
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_BIDAR-February_2017-18.sql            
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_GADAG-February_2017-18.sql
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_BIDAR-March_2017-18.sql               
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_GADAG-March_2017-18.sql
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_CHIKKABALLAPURA-December_2017-18.sql  
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_KOPPAL-February_2017-18.sql
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_CHIKKABALLAPURA-February_2017-18.sql  
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_KOPPAL-March_2017-18.sql
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_CHIKKABALLAPURA-January_2017-18.sql   
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_RAICHUR-March_2017-18.sql
psql -U klp -d ilp -f house_hold_survey_sqls/HH_survey_CHIKKABALLAPURA-March_2017-18.sql
