# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionparty',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
