# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boundaryneighbours',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electionboundary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electionneighbours',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='boundary',
            unique_together=set([('name', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='boundaryneighbours',
            unique_together=set([('boundary', 'neighbour')]),
        ),
        migrations.AlterUniqueTogether(
            name='electionboundary',
            unique_together=set([('elec_comm_code',)]),
        ),
        migrations.AlterUniqueTogether(
            name='electionneighbours',
            unique_together=set([('elect_boundary', 'neighbour')]),
        ),
        migrations.AlterUniqueTogether(
            name='electionparty',
            unique_together=set([('elect_boundary',)]),
        ),
    ]
