# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0002_auto_20170628_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.InstitutionType'),
        ),
    ]
