# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_religion_studentcategory'),
        ('boundary', '0002_auto_20170628_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('num', models.IntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.AcademicYear')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Boundary')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.StudentCategory')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Gender')),
                ('moi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_agg_moi', to='common.Language')),
                ('mt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_agg_mt', to='common.Language')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Religion')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionBoundaryAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('num', models.IntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.AcademicYear')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.StudentCategory')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.ElectionBoundary')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Gender')),
                ('moi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_agg_moi', to='common.Language')),
                ('mt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_agg_mt', to='common.Language')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Religion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='electionboundaryaggregation',
            unique_together=set([('id', 'academic_year', 'gender', 'moi', 'mt', 'religion', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='boundaryaggregation',
            unique_together=set([('id', 'academic_year', 'gender', 'moi', 'mt', 'religion', 'category')]),
        ),
    ]
