# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0004_auto_20170704_1051'),
        ('boundary', '0003_auto_20170703_2237'),
    ]

    operations = [
    ]
