# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0005_merge_20170705_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionboundary',
            name='const_ward_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='electionboundary',
            name='current_elected_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boundary.ElectionParty'),
        ),
        migrations.AlterField(
            model_name='electionboundary',
            name='current_elected_rep',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='electionboundary',
            name='elec_comm_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='electionboundary',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Boundary'),
        ),
        migrations.AlterUniqueTogether(
            name='electionboundary',
            unique_together=set([]),
        ),
    ]
