# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0006_auto_20170714_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundary',
            options={'ordering': ['name']},
        ),
    ]
