# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0007_auto_20170724_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundaryaggregation',
            options={'managed': False},
        ),
    ]
