# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0009_auto_20170724_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryHierarchy',
            fields=[
                ('admin3_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin3_id', serialize=False, to='boundary.Boundary')),
                ('admin3_name', models.CharField(max_length=300)),
                ('admin2_name', models.CharField(max_length=300)),
                ('admin1_name', models.CharField(max_length=300)),
                ('admin0_name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'mvw_boundary_hierarchy',
                'managed': False,
            },
        ),
    ]
