# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0012_auto_20170904_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicBoundaryAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
            ],
            options={
                'db_table': 'mvw_boundary_basic_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoundaryInstitutionGenderAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
            ],
            options={
                'db_table': 'mvw_boundary_school_gender_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoundarySchoolCategoryAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
                ('num_students', models.IntegerField(blank=True, db_column='num_students', null=True)),
            ],
            options={
                'db_table': 'mvw_boundary_school_category_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoundarySchoolManagementAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
                ('num_students', models.IntegerField(blank=True, db_column='num_students', null=True)),
            ],
            options={
                'db_table': 'mvw_boundary_school_mgmt_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoundarySchoolMoiAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
                ('num_students', models.IntegerField(blank=True, db_column='num_students', null=True)),
            ],
            options={
                'db_table': 'mvw_boundary_school_moi_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoundaryStudentMotherTongueAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
                ('num_students', models.IntegerField(blank=True, db_column='num_students', null=True)),
            ],
            options={
                'db_table': 'mvw_boundary_school_mt_agg',
                'managed': False,
            },
        ),
    ]
