# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0014_auto_20171208_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundarytype',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
