# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0014_auto_20171208_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryStateCode',
            fields=[
                ('char_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundary.Boundary')),
            ],
            options={
                'ordering': ['char_id'],
            },
        ),
    ]
