# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0015_boundarystatecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='lang_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
