# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-14 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0016_boundary_lang_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electionboundaryaggregation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='electionboundaryaggregation',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='electionboundaryaggregation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='electionboundaryaggregation',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='electionboundaryaggregation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='electionboundaryaggregation',
            name='moi',
        ),
        migrations.RemoveField(
            model_name='electionboundaryaggregation',
            name='mt',
        ),
        migrations.RemoveField(
            model_name='electionboundaryaggregation',
            name='religion',
        ),
        migrations.DeleteModel(
            name='ElectionBoundaryAggregation',
        ),
    ]
