# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0016_boundary_lang_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionboundary',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boundary.ElectionBoundary'),
        ),
    ]
