# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-21 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0017_auto_20180214_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicElectionBoundaryAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_students', models.IntegerField(blank=True, db_column='num_students', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
            ],
            options={
                'db_table': 'mvw_electionboundary_basic_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionBoundarySchoolCategoryAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
                ('num_students', models.IntegerField(blank=True, db_column='num_students', null=True)),
            ],
            options={
                'db_table': 'mvw_electionboundary_school_category_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionBoundarySchoolMoiAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moi', models.CharField(db_column='moi', max_length=100)),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
                ('num_students', models.IntegerField(blank=True, db_column='num_students', null=True)),
            ],
            options={
                'db_table': 'mvw_electionboundary_school_moi_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionBoundaryStudentMotherTongueAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt', models.CharField(db_column='mt', max_length=100)),
                ('num_schools', models.IntegerField(blank=True, db_column='num_schools', null=True)),
                ('num_boys', models.IntegerField(blank=True, db_column='num_boys', null=True)),
                ('num_girls', models.IntegerField(blank=True, db_column='num_girls', null=True)),
                ('num_students', models.IntegerField(blank=True, db_column='num_students', null=True)),
            ],
            options={
                'db_table': 'mvw_electionboundary_student_mt_agg',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='electionboundary',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boundary.ElectionBoundary'),
        ),
    ]
