# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-28 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0018_auto_20180227_1205'),
        ('boundary', '0018_auto_20180221_0930'),
    ]

    operations = [
    ]
