# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-25 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0019_merge_20180528_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionboundary',
            name='parent',
        ),
    ]
