# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_respondenttype_active'),
        ('boundary', '0020_remove_electionboundary_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundarystatecode',
            name='language',
            field=models.ForeignKey(default='kan', on_delete=django.db.models.deletion.CASCADE, to='common.Language'),
            preserve_default=False,
        ),
    ]
