# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0021_boundarystatecode_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionboundary',
            name='const_ward_lang_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
