update schools_student set status_id='IA' where id='5511293';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5511293' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5511290';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5511290' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5511270';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5511270' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5511274';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5511274' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5511269';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5511269' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5511272';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5511272' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5511281';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5511281' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5511252';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5511252' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2491540';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2491540' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2491548';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2491548' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2491602';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2491602' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5511203';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5511203' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2491309';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2491309' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2491917';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2491917' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5509327';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5509327' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5509280';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5509280' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5509333';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5509333' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2490616';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2490616' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5509415';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5509415' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2492893';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2492893' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2492890';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2492890' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2504789';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2504789' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2504767';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2504767' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5509395';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5509395' and academic_year_id='1819';
update schools_student set status_id='IA' where id='5509385';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='5509385' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2492389';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2492389' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2492390';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2492390' and academic_year_id='1819';
update schools_student set status_id='IA' where id='2504838';
update schools_studentstudentgrouprelation set status_id='IA' where student_id='2504838' and academic_year_id='1819';
