insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(48,'Number Recognition',654,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(48,'Place Value',656,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(48,'Addition',657,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(48,'Subtraction',658,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(48,'Multiplication',659,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(48,'Addition',666,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(48,'Subtraction',667,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(48,'Division',669,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(49,'Number Recognition',674,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(49,'Addition',676,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(49,'Subtraction',677,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(49,'Multiplication',678,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(49,'Division',679,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(49,'Place Value',684,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(50,'Number Recognition',694,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(50,'Addition',695,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(50,'Subtraction',696,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(50,'Multiplication',697,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(50,'Division',698,1);
insert into assessments_competencyquestionmap(questiongroup_id,key,question_id,max_score) values(50,'Place Value',704,1);
